### ISSUE TITLE
拉下来，后跑不起来，大家有遇到类似问题吗？

### ISSUE THREAD

**Issue by turbochoo** [Exrick/x-boot#20]
Field logDao in cn.exrick.xboot.modules.base.serviceimpl.elasticsearch.EsLogServiceImpl required a bean of type 'cn.exrick.xboot.modules.base.dao.elasticsearch.EsLogDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'cn.exrick.xboot.modules.base.dao.elasticsearch.EsLogDao' in your configuration.

**Comment by Exrick** [comment]
抱歉 近期将提交并更新文档修复该问题
解决方案1：启动elasticsearch 6.x版本
解决放案2：
- 找到EsLogServiceImpl修改
``` java
@Autowired(required = false)
private EsLogDao logDao;
```
- 修改配置文件
``` yml
spring:
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      # 暂未使用ES 关闭其存储
      repositories:
        enabled: false
```
